order/urls.py
from django.conf.urls import url
from django.http import HttpResponse

urlpatterns = [
    url(r'^checkout/', lambda request: HttpResponse("Checkout", content_type="text/plain")),
    url(r'^process/', lambda request: HttpResponse("Processing order", content_type="text/plain")),
    url(r'^(?P<pk>[0-9]+)/', lambda request: HttpResponse("Display your order", content_type="text/plain")),
]

profile/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy

from profile import views
from django.contrib.auth import views as admin

urlpatterns = [
    url(r'^$', views.Overview.as_view(), name="profile"),
    url(r'orders/$', views.Orders.as_view(), name="profile_orders"),
    url(r'order/(?P<pk>[0-9]+)/$', views.OrderDetail.as_view(), name="profile_orderdetail"),
    # Authentication
    url(r'^login/$', admin.LoginView.as_view(), name='login'),
    url(r'^logout/$', admin.LogoutView.as_view(), name='logout'),
    url(r'^password_change/$', views.PasswordChangeWithMessageView.as_view(success_url=reverse_lazy('profile')),
        name='password_change'),
    url(r'^register/$', views.RegistrationView.as_view(), name='registration_register'),
    url(r'^edit/$', views.ProfileEditView.as_view(), name='edit_profile'),
    url(r'^cart/$', views.user_cart, name='profile_cart'),
]

shop/urls.py
from django.conf.urls import url
from django.http import HttpResponse

from shop import views

urlpatterns = [
    url(r'^$', views.Overview.as_view(), name='shop'),
    url(r'search/$', views.search_view, name='shop_search'),
    url(r'checkout/$', views.checkout, name='shop_checkout'),
    url(r'checkout/confirm/$', views.checkout_confirm, name='shop_checkout_confirm'),
    url(r'product/(?P<pk>[0-9]+)/$', views.product_view, name='shop_detail'),
    url(r'product/(?P<pk>[0-9]+)/rate/(?P<rating>[0-1])', views.rate_product, name='product_rate'),
    url(r'product/(?P<pk>[0-9]+)/add_to_cart/$', views.add_to_cart, name='shop_add_to_cart'),
    url(r'category/$', views.CategoryOverview.as_view(), name='shop_category_overview'),
    url(r'category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='shop_category'),
]

shopstore/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponse

from home import views as home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shop/', include('shop.urls')),
    url(r'^order/', include('order.urls')),
    url(r'^profile/', include('profile.urls')),  # Order and edit too
    url(r'^$', home.IndexView.as_view(), name='home'),
]

order/models.py
from django.utils import timezone

from profile.models import User
from django.db import models
from django.db.models import Sum, F

from shop.models import Product


class Order(models.Model):

    STATUS = (
        ("0", 'Verified'),
        ("1", 'Shipped'),
        ("2", 'Received'),
        ("3", 'Refunded'),
    )

    ordered = models.DateTimeField(default=timezone.now)
    order_status = models.CharField(max_length=1, choices=STATUS, default='0')
    user = models.ForeignKey(User)

    @property
    def items(self):
        return self.orderproduct_set.aggregate(order_cost=Sum(
            F('cost') *
            F('quantity'),
            output_field=models.PositiveIntegerField()
        ))

    def __str__(self):
        return "Order: " + str(self.pk)


class OrderProduct(models.Model):
    quantity = models.IntegerField()
    order = models.ForeignKey(Order)
    product = models.ForeignKey(Product)
    cost = models.IntegerField()

    def __str__(self):
        return "Order id: {}, Product id: {}, Quantity: {}".format(self.order.pk, self.product.pk, self.quantity)

orders/models.py
from django.db import models

from shop.models import Product


class Order(models.Model):

    STATUS = (
        (0, 'Verified'),
        (1, 'Shipped'),
        (2, 'Received'),
    )

    ordered = models.BooleanField()
    order_status = models.CharField(max_length=1, choices=STATUS)


class OrderProduct(models.Model):
    quantity = models.IntegerField()
    order = models.ForeignKey(Order)
    product = models.ForeignKey(Product)

profile/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30)
    last_name = models.CharField(_('last name'), max_length=30)
    personal_id = models.CharField(max_length=13,
                                   help_text=_('Personal ID has to follow style yyyyMMdd-xxxx.'),
                                   unique=True,
                                   validators=[RegexValidator(regex='^\d{8}-\d{4}$',
                                                              message='Personal ID has to follow style yyyyMMdd-xxxx',
                                                              code='nomatch')])
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    zip_code = models.CharField(max_length=5,
                                validators=[RegexValidator(regex='^\d{5}$',
                                                           message='Post number has to be 5 long',
                                                           code='nomatch')])
    phone_number = models.CharField(max_length=14)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

profile/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from profile.models import User


class ExtendedRegistrationForm(UserCreationForm):

    class Meta:
        fields = [
            User.USERNAME_FIELD,
            'email',
            'password1',
            'password2',
            'first_name',
            'last_name',
            'personal_id',
            'phone_number',
            'address',
            'city',
            'zip_code',
        ]
        model = User

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class EditProfileForm(UserChangeForm):

    class Meta:
        fields = [
            User.USERNAME_FIELD,
            'email',
            'password',
            'phone_number',
            'address',
            'city',
            'zip_code',
        ]
        model = User

    def save(self, commit=True):
        user = super(UserChangeForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

profile/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, FormView, UpdateView

from order.models import Order
from profile import forms
from shop.models import CartItem, Cart


class Overview(LoginRequiredMixin, DetailView):
    template_name = 'profile/overview.html'

    def get_object(self, queryset=None):
        return self.request.user


class Orders(LoginRequiredMixin, DetailView):
    template_name = 'profile/orders.html'

    def get_object(self, queryset=None):
        return self.request.user


class OrderDetail(LoginRequiredMixin, DetailView):
    template_name = 'profile/orderdetail.html'
    model = Order


class RegistrationView(FormView):
    template_name = 'registration/registration_form.html'
    form_class = forms.ExtendedRegistrationForm
    success_url = reverse_lazy('profile')

    def form_valid(self, form):
        form.save()

        messages.info(self.request, "Thanks for registering. You are now logged in.")
        new_user = authenticate(email=form.cleaned_data['email'],
                                password=form.cleaned_data['password1'],
                                )
        login(self.request, new_user)
        return super(RegistrationView, self).form_valid(form)


class ProfileEditView(LoginRequiredMixin, UpdateView):
    template_name = 'profile/edit.html'

    form_class = forms.EditProfileForm
    success_url = reverse_lazy('profile')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        form.save()

        messages.info(self.request, "Profile has been saved.")
        return super(ProfileEditView, self).form_valid(form)


class PasswordChangeWithMessageView(PasswordChangeView):
    def form_valid(self, form):
        messages.success(self.request, "Your password has been changed.")
        return super(PasswordChangeWithMessageView, self).form_valid(form)


@login_required()
def user_cart(request):
    # If user doesn't have a cart in DB, display empty
    if not hasattr(request.user, 'cart'):
        return render(request, 'profile/cart.html', {
            'cart': None,
            'formset': None
        })

    cart = request.user.cart

    cartitem_form_set = inlineformset_factory(Cart, CartItem, fields=('quantity',), extra=0)

    if request.method == "POST":
        formset = cartitem_form_set(request.POST, request.FILES, instance=cart)
        if formset.is_valid():
            messages.info(request, message='Cart updated')
            formset.save()
        else:
            messages.warning(request, message='Form is invalid')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    else:
        formset = cartitem_form_set(instance=cart)
    return render(request, 'profile/cart.html', {
        'cart': cart,
        'formset': formset
    })

templates/profile/cart.html
{% extends "base.html" %}

{% block title %}Cart{% endblock %}

{% block content %}
    <div class="justify-content-md-center row">
        <div class="col col-md-9 col-lg-8 col-xl-7">
            {#{{ formset }}#}
            <h1>Cart</h1>
            {% if formset.forms %}
                <form method="post" action="{% url "profile_cart" %}" class="form-inline">
                    {% csrf_token %}
                    <table class="table table-hover text-right">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Article</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Cost</th>
                            <th scope="col">Remove</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for cartitem in formset %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td><a href="#">{{ cartitem.instance.product.name }}</a></td>
                                <td>{{ cartitem.instance.price_snapshot }}&nbsp;kr</td>
                                <td>
                                    <input class="input-group-addon form-control"
                                           value="{{ cartitem.quantity.value|default_if_none:"" }}"
                                           type="number" title="{{ cartitem.quantity.label }}"
                                           min="1"
                                           {% if cartitem.instance.product.inventory > 0 %}
                                               max="{{ cartitem.instance.product.inventory }}"
                                           {% endif %}
                                           name="{{ cartitem.quantity.html_name }}"/>
                                </td>
                                <td>
                                    {{ cartitem.instance.total_cost }}&nbsp;kr
                                    {{ cartitem.id }}
                                </td>
                                <td>
                                    {{ cartitem.DELETE }}
                                </td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <th scope="row" colspan="5" class="text-right">
                                Total cost: <br>
                                {{ cart.items.cart_cost|default_if_none:"0" }}&nbsp;kr
                            </th>
                        </tr>
                        </tbody>
                    </table>
                    {{ formset.management_form }}
                    <div class="ml-auto">
                        <input type="submit" value="Update cart" class="btn btn-secondary">
                        <a href="{% url "shop_checkout" %}" class="btn btn-primary text-light">Buy</a>
                    </div>
                </form>
            {% else %}
                <div>
                    Cart is empty
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/profile/edit.html
{% extends "base.html" %}

{% block title %}Edit profile{% endblock %}

{% block content %}
    <div class="justify-content-md-center row">
        <div class="border rounded pb-2 bg-white col col-md-6 col-lg-4 col-xl-3">
            {% if form.errors %}
                <div class="alert alert-danger mt-3" role="alert">Your username and password didn't match. Please try
                    again.
                </div>
            {% endif %}

            <form method="post" action="{% url 'edit_profile' %}">
                {% csrf_token %}
                <h1>Change profile</h1>
                <div class="form-group">
                    <label class="col-form-label" for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                    <input class="form-control" id="{{ form.email.id_for_label }}" maxlength="254"
                           name="{{ form.email.html_name }}" type="text" placeholder="{{ form.email.label }}" value="{{ form.email.value|default_if_none:"" }}"/>
                    {% if form.email.help_text %}
                        <small class="form-text">{{ form.email.help_text|safe }}</small>
                    {% endif %}
                    {{ form.email.errors }}
                </div>
                <div class="form-group">
                    <h2>Personal info</h2>

                    <label class="col-form-label"
                           for="{{ form.phone_number.id_for_label }}">{{ form.phone_number.label }}</label>
                    <input class="form-control" id="{{ form.phone_number.id_for_label }}" maxlength="254"
                           name="{{ form.phone_number.html_name }}" type="text"
                           placeholder="{{ form.phone_number.label }}" value="{{ form.phone_number.value|default_if_none:"" }}"/>
                    {{ form.phone_number.errors }}
                </div>
                <div class="form-group">
                    <h2>Address</h2>

                    <label class="col-form-label" for="{{ form.address.id_for_label }}">{{ form.address.label }}</label>
                    <input class="form-control" id="{{ form.address.id_for_label }}" maxlength="254"
                           name="{{ form.address.html_name }}" type="text" placeholder="{{ form.address.label }}" value="{{ form.address.value|default_if_none:"" }}"/>
                    {{ form.address.errors }}

                    <label class="col-form-label" for="{{ form.city.id_for_label }}">{{ form.city.label }}</label>
                    <input class="form-control" id="{{ form.city.id_for_label }}" maxlength="254"
                           name="{{ form.city.html_name }}" type="text" placeholder="{{ form.city.label }}" value="{{ form.city.value|default_if_none:"" }}"/>
                    {{ form.city.errors }}

                    <label class="col-form-label"
                           for="{{ form.zip_code.id_for_label }}">{{ form.zip_code.label }}</label>
                    <input class="form-control" id="{{ form.zip_code.id_for_label }}" maxlength="254"
                           name="{{ form.zip_code.html_name }}" type="text" placeholder="{{ form.zip_code.label }}" value="{{ form.zip_code.value|default_if_none:"" }}"/>
                    {{ form.zip_code.errors }}
                </div>
                <input class="btn btn-primary" type="submit" value="Save"/>
                <a href="{% url "password_change" %}" class="btn btn-secondary">Change password</a>
                <input type="hidden" name="next" value="{{ next }}"/>
            </form>
        </div>
    </div>
{% endblock %}

templates/profile/orderdetail.html
{% extends "base.html" %}

{% block title %}Order {{ order.pk }}{% endblock %}

{% block content %}
    <div class="justify-content-md-center row">
        <div class="col col-md-9 col-lg-8 col-xl-7">
            <h1>Order {{ order.pk }}</h1>
            <p>
                Date ordered: {{ order.ordered }}
            </p>
            <p>
                Order status: {{ order.get_order_status_display }}
            </p>
            <p>
                Total cost: {{order.items.order_cost|default_if_none:"0"}} kr
            </p>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Cost</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_product in order.orderproduct_set.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ order_product.product.name }}</td>
                            <td>{{ order_product.quantity }}</td>
                            <td>{{ order_product.cost }} kr</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/profile/orders.html
{% extends "base.html" %}

{% block title %}Orders{% endblock %}

{% block content %}
    <div class="justify-content-md-center row">
        <div class="col col-md-9 col-lg-8 col-xl-7">
            <h1>Orders</h1>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Date ordered</th>
                        <th scope="col">Order status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in user.order_set.all %}
                        <tr>
                            <th scope="row"><a href="{% url "profile_orderdetail" order.pk %}">{{ order.id }}</a></th>
                            <td>{{ order.ordered }}</td>
                            <td>{{ order.get_order_status_display }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/profile/overview.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}
    <div class="justify-content-center row">
        <div class="col col-sm-8 col-md-4 col-lg-3 col-xl-2">
            <h1>Hello {{ user.get_short_name }}</h1>
            <div>
                <p>Email: {{ user.email }}</p>
                <p>Address: {{ user.address }}</p>
                <p>City: {{ user.city }}</p>
                <p>Zip: {{ user.zip_code }}</p>
                <p>Phone number: {{ user.phone_number }}</p>
            </div>
            <div>
                <a class="btn btn-primary" href="{% url 'edit_profile' %}">Edit</a>
            </div>
        </div>
        <div class="w-100 d-sm-block d-md-none"></div>
        <div class="col col-sm-8 col-md-8 col-lg-8 col-xl-7">
            <h1>Orders</h1>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Date ordered</th>
                        <th scope="col">Order status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in user.order_set.all %}
                        <tr>
                            <th scope="row"><a href="{% url "profile_orderdetail" order.pk %}">{{ order.id }}</a></th>
                            <td>{{ order.ordered }}</td>
                            <td>{{ order.get_order_status_display }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="3" class="text-center"><a href="{% url "profile_orders" %}">More</a></th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}